language: node_js
node_js:
  - '12'

script:
  - yarn build

# install:
#   - npm install -g firebase-tools

# safelist
branches:
  only:
    - main
    - develop

jobs:
  include:
    - stage: deploy
    - script: cd functions && (npm i && npm run deploy:ci)
