language: node_js
node_js:
  - '12'

# script:
#   - yarn run build

# install:
#   - npm install -g firebase-tools

# safelist
branches:
  only:
    - master
    - develop

jobs:
  include:
    - stage: deploy
    - script: (cd functions && (npm i && npm run deploy:ci)) & yarn build
